<?php

namespace Webkul\ShopifyBundle\Repository;

/**
 * SettingConfigurationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SettingConfigurationRepository extends \Doctrine\ORM\EntityRepository
{
    // public function __construct($em, $class)
    // {
    //     parent::__construct($em, $em->getClassMetadata($class));
    //     $this->em = $em;
    //     $this->entityName = $class;
    // }
}
