services:
    # connector service
    shopify.connector.service:
        public: true
        class: 'Webkul\ShopifyBundle\Services\ShopifyConnector'
        arguments:
            - '@router'
            - '@doctrine.orm.entity_manager'
            - '@pim_catalog.repository.attribute'
            - '@pim_catalog.repository.attribute_option'
            - '@pim_catalog.repository.category'
            - '@pim_catalog.repository.product'
            - '@pim_catalog.repository.product_model'
            - '@pim_catalog.repository.family_variant'
            - '@pim_catalog.repository.family'
            - '@pim_catalog.factory.family_variant'
            - '@pim_catalog.updater.family_variant'
            - '@pim_catalog.query.product_query_builder_factory'
            - '@pim_catalog.query.product_model_query_builder_factory'
            - '@pim_catalog.normalizer.standard.attribute_option'
            - '@pim_catalog.repository.group'
            - '@pim_catalog.repository.locale'
            - '@pim_serializer'
        calls:
            - [setCredentialRepository, ['@webkul_shopify.export_mapping.repository']]
            - [setJobLogger, ['@webkul_shopify_jobs.logger']]
            - [setPimSerializer, ['@pim_serializer']]
            - [setMatchedProductLogger, ['@webkul_shopify_jobs.import_matched.product.logger']]
            - [setUnmatchedProductLogger, ['@webkul_shopify_jobs.import_unmatched.product.logger']]

    # api logger service to generate the api import / export logs
    webkul_shopify_jobs.logger:
        public: true
        class: 'Webkul\ShopifyBundle\Logger\ApiLogger'
        arguments:
            - 'webkul_shopify'
        calls:
            - [pushHandler, ['@webkul_shopify_logger_handler']]

    webkul_shopify_logger_handler:
        public: true
        class: Monolog\Handler\StreamHandler
        arguments: ['%kernel.logs_dir%/webkul_shopify_batch.%kernel.environment%.log', 'info']

    # product import logger service to generate log for matched sku product
    webkul_shopify_jobs.import_matched.product.logger:
        public: true
        class: 'Webkul\ShopifyBundle\Logger\ApiLogger'
        arguments:
            - 'webkul_shopify'
        calls:
            - [pushHandler, ['@webkul_shopify_logger_import_matched_handler']]

    webkul_shopify_logger_import_matched_handler:
        public: true
        class: Monolog\Handler\StreamHandler
        arguments: ['%kernel.logs_dir%/webkul_shopify_import_matched_sku_product.%kernel.environment%.log', 'info']

    # product import logger service to generate log for unmatched sku product
    webkul_shopify_jobs.import_unmatched.product.logger:
        public: true
        class: 'Webkul\ShopifyBundle\Logger\ApiLogger'
        arguments:
            - 'webkul_shopify'
        calls:
            - [pushHandler, ['@webkul_shopify_logger_import_unmatched_handler']]

    webkul_shopify_logger_import_unmatched_handler:
        public: true
        class: Monolog\Handler\StreamHandler
        arguments: ['%kernel.logs_dir%/webkul_shopify_import_unmatched_sku_product.%kernel.environment%.log', 'info']


    # formate the tags according to the mapping
    webkul_shopify_tags_formatter:
        public: true
        class: Webkul\ShopifyBundle\Classes\DataFormatter\Export\TagsFormatter
        arguments:
            - '@shopify.connector.service'
            - '@pim_serializer'

    # formate the product data according to mapping
    webkul_shopify_product_data_formatter:
        public: true
        class: Webkul\ShopifyBundle\Classes\DataFormatter\Export\ProductDataFormatter
        arguments:
            - '@shopify.connector.service'

    # image File controller to generate full image resolution image url
    webkul.shopify_connector.controller.imagefile:
        public: true
        class: Webkul\ShopifyBundle\Controller\ImageFileController
        arguments:
            - '@akeneo_file_storage.file_storage.filesystem_provider'
            - '@akeneo_file_storage.repository.file_info'
            - ['catalogStorage']

    #datagrid for akeneo shopify connector
    webkul-product-export-mapping-grid.datasource.credentails:
        public: true
        class: Webkul\ShopifyBundle\DataSource\CredentailsDatasource
        arguments:
            - '@webkul_shopify.export_mapping.repository'
            - '@pim_datagrid.datasource.result_record.hydrator.default'
        tags:
            - { name: oro_datagrid.datasource, type: custom_datasource_credentials }

    webkul.pre_save.product_events:
        public: true
        class: Webkul\ShopifyBundle\EventListener\ProductListener
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@shopify.connector.service'
        tags:
            - { name: kernel.event_listener, event: akeneo.storage.pre_save, method: preSaveProductAndUpdateMapping }