parameters:
  pim_datagrid.extension.mass_action.handler.webkul_shopify_export_mapping_delete.class:  Webkul\ShopifyBundle\Extension\MassAction\Handler\DeleteShopifyExportMappingsMassActionHandler
  # pim_datagrid.extension.mass_action.type.delete.class: Oro\Bundle\PimDataGridBundle\Extension\MassAction\Actions\Ajax\DeleteMassAction

services:
  pim_datagrid.extension.mass_action.handler.webkul_shopify_export_mapping_delete:
    class: '%pim_datagrid.extension.mass_action.handler.webkul_shopify_export_mapping_delete.class%'
    arguments:
      - '@pim_datagrid.datasource.result_record.hydrator.object_id'
      - '@translator'
      - '@event_dispatcher'
    tags:
      - { name: pim_datagrid.extension.mass_action.handler, alias: webkul_shopify_connector_export_mapping_mass_delete, type: mass_delete }
    # pim_datagrid.extension.mass_action.type.webkul_shopify_mass_delete:
    #   public: true
    #   class: '%pim_datagrid.extension.mass_action.type.delete.class%'
    #   shared: false
    #   tags:
    #     - { name: oro_datagrid.extension.mass_action.type, type: mass_delete }

  webkul_shopify.controller.rest.mass_delete:
    public: true
    class: 'Webkul\ShopifyBundle\Extension\MassAction\Handler\Akeneo4\MassDeleteController'
    arguments:
      - '@webkul_shopify.export_mapping.repository'
      - '@doctrine.orm.entity_manager'