config:
    paths:
        # Controller
        shopify/controller/configuration: shopify/js/controller/configuration
        shopify/form/configuration: shopify/js/form/configuration


        shopify/form/configuration/create/form: shopify/js/form/configuration/create/form
        shopify/controller/configuration/datagrid_mapping/index: shopify/js/controller/configuration/datagrid_mapping/index
        # tabs
        # shopify/form/configuration/tab/overview: shopify/js/form/configuration/tab/overview
        shopify/form/configuration/tab/documentation: shopify/js/form/configuration/tab/documentation
        shopify/form/configuration/tab/credential: shopify/js/form/configuration/tab/credential
        shopify/form/configuration/tab/export-settings: shopify/js/form/configuration/tab/exportsettings
        shopify/form/configuration/tab/import-settings: shopify/js/form/configuration/tab/importsettings
        shopify/form/configuration/tab/other-settings: shopify/js/form/configuration/tab/othersettings
        shopify/form/configuration/create/modal: shopify/js/form/configuration/create/modal
        # buttons
        shopify/form/configuration/save: shopify/js/form/configuration/save
        shopify/form/configuration/jobs: shopify/js/form/configuration/jobs
        shopify/form/configuration/import/jobs: shopify/js/form/configuration/importjobs
        shopify/job/export/exportProfile: shopify/js/job/export/exportProfile
        #mass action
        oro/datagrid/mass_delete-action: shopify/js/akeneo4/shopify_mass_delete

        # Templates
        # shopify/template/configuration/tab/overview: shopify/templates/configuration/tab/overview.html
        shopify/template/configuration/tab/documentation: shopify/templates/configuration/tab/documentation.html
        shopify/template/configuration/tab/credential: shopify/templates/configuration/tab/credential.html
        shopify/template/configuration/tab/exportsettings: shopify/templates/configuration/tab/exportsettings.html
        shopify/template/configuration/tab/importsettings: shopify/templates/configuration/tab/importsettings.html
        shopify/template/configuration/tab/othersettings: shopify/templates/configuration/tab/othersettings.html
        shopify/template/configuration/locales: shopify/templates/configuration/locales.html
        shopify/template/configuration/currencies: shopify/templates/configuration/currencies.html
        shopify/template/configuration/family: shopify/templates/configuration/family.html
        shopify/template/job/export/credentials: shopify/templates/job/export/credentials.html
        shopify/template/common/password: shopify/templates/common/password.html
        shopify/template/common/meta: shopify/templates/common/meta.html
        shopify/template/configuration/tab/storeMapping: shopify/templates/configuration/tab/storeMapping.html
        shopify/template/job/default: shopify/templates/job/default-template.html
        # export mapping
        shopify/template/configuration/exportmapping/type: shopify/templates/configuration/exportmapping/type.html
        shopify/template/configuration/exportmapping/apiurl: shopify/templates/configuration/exportmapping/apiurl.html
        # other
        shopify/form/configuration/locales: shopify/js/form/configuration/locales
        shopify/form/configuration/currencies: shopify/js/form/configuration/currencies
        shopify/form/configuration/family: shopify/js/form/configuration/family
        shopify/job/export/credentials: shopify/js/job/export/credentials
        shopify/common/password: shopify/js/common/password
        shopify/common/meta: shopify/js/common/meta
        shopify/form/configuration/tab/storeMapping: shopify/js/form/configuration/tab/storeMapping
        # job inventory locations
        shopify/job/common/edit/field/locations: shopify/js/job/common/edit/field/locations
        shopify/template/common/edit/field/locations: shopify/templates/common/edit/field/locations.html


        #forms
        shopify/form/configuration/exportmapping/modal: shopify/js/form/configuration/exportmapping/modal
        shopify/form/configuration/exportmapping/type: shopify/js/form/configuration/exportmapping/type
        shopify/configuration/exportmapping/product/akeneo: shopify/js/form/configuration/exportmapping/product/akeneo
        webkul/shopifyconnector/form/configuration/exportmapping/category/akeneo: shopify/js/form/configuration/exportmapping/category/akeneo
        webkul/shopifyConnector/form/configuration/exportmapping/apiurl: shopify/js/form/configuration/exportmapping/apiurl
        webkul/shopifyConnector/form/configuration/exportmapping/product/select: shopify/js/form/configuration/exportmapping/product/select
        webkul/shopifyConnector/form/configuration/exportmapping/category/select: shopify/js/form/configuration/exportmapping/category/select
        webkul/shopifyConnector/form/configuration/exportmapping/product/shopify-select: shopify/js/form/configuration/exportmapping/product/shopify-select
        webkul/shopifyConnector/form/configuration/exportmapping/category/shopify-select: shopify/js/form/configuration/exportmapping/category/shopify-select
        webkul/shopifyConnector/form/configuration/exportmapping/baseSelect: shopify/js/form/configuration/exportmapping/baseSelect
        #History
        shopify/history/class: shopify/js/job/common/history
        shopify/form/configuration/credentials/edit: shopify/js/form/configuration/credentials/edit 
    config:
        pim/controller-registry:
            controllers:
                webkul_shopify_connector_configuration: #Router for above module
                    aclResourceId: webkul_shopify_connector_configuration
                    module: shopify/controller/configuration     #Module
                webkul_shopify_data_grid:
                    module: shopify/controller/configuration/datagrid_mapping/index
                webkul_shopify_credentials_edit:
                    module: shopify/form/configuration/credentials/edit
                # webkul_shopify_credentials_change_status:
                #     module: pim/controller/redirect
        shopify/form/configuration/save:
            route: webkul_shopify_connector_configuration_post

        pim/fetcher-registry:
            fetchers:
                shopify-fields:
                    module: pim/base-fetcher
                    options:
                        urls:
                            list: webkul_shopify_connector_configuration_action
                shopify-quickcurrencies:
                    module: pim/base-fetcher
                    options:
                        urls:
                            list: webkul_shopify_connector_configuration_active_currencies
                shopify-locations:
                    module: pim/base-fetcher
                    options:
                        urls:
                            list: webkul_shopify_connector_configuration_get_inventory_location
                akeneo-product:
                    module: pim/base-fetcher
                    options:
                        urls:
                            list: webkul_shopify_connector_configuration_get_akeneo_product
                shopify-product:
                    module: pim/base-fetcher
                    options:
                        urls:
                            list: webkul_shopify_connector_configuration_get_shopify_product
                akeneo-category:
                    module: pim/base-fetcher
                    options:
                        urls:
                            list: webkul_shopify_connector_get_akeneo_category
                shopify-category:
                    module: pim/base-fetcher
                    options:
                        urls:
                            list: webkul_shopify_connector_get_shopify_category
                shopify-apiurl:
                    module: pim/base-fetcher
                    options:
                        urls:
                            list: webkul_shopify_connector_get_api_url
                shopify-product-relatedid:
                    module: pim/base-fetcher
                    options:
                        urls:
                            list: webkul_shopify_connector_get_shopify_relatedid
                akeneo-shopify-history-class:
                    module: pim/base-fetcher
                    options:
                        urls:
                            list: webkul_shopify_get_history_class
                shopify-profiles:
                    module: pim/base-fetcher
                    options:
                        urls:
                            list: webkul_shopify_credentials_get_all
