extensions:
    webkul-shopify-credential-edit-form:
        module:  shopify/form/configuration

    webkul-shopify-credential-edit-user-navigation:
        module: pim/menu/user-navigation
        parent: webkul-shopify-credential-edit-form
        targetZone: user-menu
        config:
            userAccount: pim_menu.user.user_account
            logout: pim_menu.user.logout
    
    webkul-shopify-credential-edit-title:
        module: pim/common/grid-title
        parent: webkul-shopify-credential-edit-form
        targetZone: title
        config:
            title: webkul_shopify.edit.credential
            countable: false

    # Save Button
    webkul-shopify-credential-edit-save:
        module: shopify/form/configuration/save
        parent: webkul-shopify-credential-edit-form
        targetZone: buttons
        position: 100
        config:
            postUrl: webkul_shopify_credentials_update

    # Store Mapping
    webkul-shopify-credential-edit-store-mapping:
        module: shopify/form/configuration/tab/storeMapping
        parent: webkul-shopify-credential-edit-form
        targetZone: content
        position: 130

    webkul-shopify-connector-credential-edit-state:
        module: pim/form/common/state
        parent: webkul-shopify-credential-edit-form
        targetZone: state
        position: 900
        config:
            entity: pim_enrich.entity.product.title
