extensions:
     # Attribute Mapping Model
    webkul-shopify-connector-create-instance-modal:
        module: shopify/form/configuration/create/modal
        config:
            labels:
                title: webkul_shopify_connector.create_popin.title
                subTitle: webkul_shopify_connector.item.credential
            picture: illustrations/Groups.svg
            successMessage: pim_enrich.entity.credential.message.created
            editRoute: webkul_shopify_credentials_edit
            postUrl: webkul_shopify_credentials_create

    webkul-shopify-connector-create-instance-modal-host:
        module: shopify/form/configuration/create/form
        parent: webkul-shopify-connector-create-instance-modal
        targetZone: fields
        position: 10
        config:
            labels:
                title: webkul_shopify_connector.create_popin.title
                subTitle: webkul_shopify_connector.item.export_mapping
            identifier: shopUrl
            label: webkul_shopify_connector.shopUrl

