Webkul\ShopifyBundle\Entity\CredentialsConfig:
    type: entity
    table: wk_shopify_credentials_config
    repositoryClass: Webkul\ShopifyBundle\Repository\CredentialsConfigRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        shopUrl:
            type: string
            length: 255
        apiPassword:
            type: string
            length: 255
        apiKey:
            type: string
            length: 255
        active:
            type: boolean
            options:
                default: 0
        apiVersion:
            type: string
            length: 255
            nullable: true
        defaultSet:
            type: boolean
            options:
                default: 0
        resources:
            type: string
            length: 255
            nullable: true
        extras:
            type: string
            length: 255
            nullable: true
    lifecycleCallbacks: {  }
