Webkul\ShopifyBundle\Entity\SettingConfiguration:
    type: entity
    table: shopify_setting_configuration_value
    repositoryClass: Webkul\ShopifyBundle\Repository\SettingConfigurationRepository
    indexes:
        shopify_setting_configuration:
            columns: [ name, section]
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            nullable: true
            length: 255
        section:
            type: string
            length: 255
            nullable: true
        value:
            type: text
            nullable: true
        