datagrid:
    webkul-shopify-credentials-mapping-grid:
        extended_entity_name: Webkul\ShopifyBundle\Entity\CredentialsConfig
        options:
            entityHint: CredentialsConfig
            manageFilters: false
        source:
            # acl_resource: webkul_shopify_connector_configuration
            type: pim_datasource_default
            repository_method: createDatagridQueryBuilder
            entity: 'Webkul\ShopifyBundle\Entity\CredentialsConfig'
            query:
                select:
                    - rd.id
                    - rd.shopUrl
                    - rd.apiPassword
                    - rd.apiKey
                    - rd.active    
                    - rd.defaultSet
                from:
                    - { table: 'Webkul\ShopifyBundle\Entity\CredentialsConfig', alias: rd }
        columns:
            shopUrl:
                label: shopify.form.properties.shop_url.title
                frontend_type: label
            active:
                label: Activated
                type: twig
                template: PimDataGridBundle:Property:activated.html.twig
                frontend_type: html
            defaultSet:
                label: Default for QuickExport
                type: twig
                template: PimDataGridBundle:Property:activated.html.twig
                frontend_type: html
        sorters:
            columns:
                shopUrl:
                    data_name: rd.shopUrl
                active:
                    data_name: rd.active
            default:
                url: '%oro_datagrid.extension.orm_sorter.class%::DIRECTION_ASC'
        filters:
            columns:
                shopUrl:
                    type: search
                    data_name: rd.shopUrl
                active:
                    type:      boolean
                    label:     Activated
                    data_name: rd.active
        properties:
            id: ~
            edit_link:
                type: url
                route: webkul_shopify_credentials_edit
                params:
                    - id
            toggle_link:
                type: url
                route: webkul_shopify_credentials_change_status
                params:
                    - id
            delete_link:
                type: url
                route: webkul_shopify_credentials_delete
                params:
                    - id
            quick_export_default_link:
                type: url
                route: webkul_shopify_credentials_change_default_quickexport
                params:
                    - id
        actions:
            toggle:
                launcherOptions:
                    className: AknIconButton AknIconButton--small AknIconButton--switch
                type:         toggle-product
                label:        Change status
                link:         toggle_link
                # acl_resource: webkul_shopify_connector_configuration
            edit:
                launcherOptions:
                    className: AknIconButton AknIconButton--small AknIconButton--edit
                type:      navigate
                label:     Edit
                link:      edit_link
                # acl_resource: webkul_shopify_connector_configuration
                rowAction: true
            delete:
                launcherOptions:
                    className: AknIconButton AknIconButton--small AknIconButton--trash
                type:          delete
                label:         Delete
                link:          delete_link
                # acl_resource:  webkul_shopify_connector_configuration
            defaultSet:
                launcherOptions:
                    className: AknIconButton AknIconButton--small AknIconButton--switch
                type: toggle-product
                label:        Set Default for Quick Export
                link:         quick_export_default_link
                # acl_resource: webkul_shopify_connector_configuration